#https://www.jianshu.com/p/8d3716bf2e9b
arg <- commandArgs(T)

test0 <- read.table("0/test.db.predict.xls" , header=TRUE)
test1 <- read.table("1/test.db.predict.xls" , header=TRUE)
test2 <- read.table("2/test.db.predict.xls" , header=TRUE)
test3 <- read.table("3/test.db.predict.xls" , header=TRUE)
test4 <- read.table("4/test.db.predict.xls" , header=TRUE)
test5 <- read.table("5/test.db.predict.xls" , header=TRUE)
test6 <- read.table("6/test.db.predict.xls" , header=TRUE)
test7 <- read.table("7/test.db.predict.xls" , header=TRUE)
test8 <- read.table("8/test.db.predict.xls" , header=TRUE)
test9 <- read.table("9/test.db.predict.xls" , header=TRUE)



train0 <- read.table("0/train.db.predict.xls" , header=TRUE)
train1 <- read.table("1/train.db.predict.xls" , header=TRUE)
train2 <- read.table("2/train.db.predict.xls" , header=TRUE)
train3 <- read.table("3/train.db.predict.xls" , header=TRUE)
train4 <- read.table("4/train.db.predict.xls" , header=TRUE)
train5 <- read.table("5/train.db.predict.xls" , header=TRUE)
train6 <- read.table("6/train.db.predict.xls" , header=TRUE)
train7 <- read.table("7/train.db.predict.xls" , header=TRUE)
train8 <- read.table("8/train.db.predict.xls" , header=TRUE)
train9 <- read.table("9/train.db.predict.xls" , header=TRUE)

library(pROC)
library(ggplot2)
roc0 = roc(test0$Result, test0$Ratio ,    auc=TRUE,    grid=TRUE, print.auc=TRUE, show.thres=TRUE, ci=TRUE, boot.n=100, ci.alpha=0.9, stratified=FALSE, smooth=TRUE)
roc1 = roc(test1$Result, test1$Ratio , smooth=TRUE)
roc2 = roc(test2$Result, test2$Ratio , smooth=TRUE)
roc3 = roc(test3$Result, test3$Ratio , smooth=TRUE)
roc4 = roc(test4$Result, test4$Ratio , smooth=TRUE)
roc5 = roc(test5$Result, test5$Ratio , smooth=TRUE)
roc6 = roc(test6$Result, test6$Ratio , smooth=TRUE)
roc7 = roc(test7$Result, test7$Ratio , smooth=TRUE)
roc8 = roc(test8$Result, test8$Ratio , smooth=TRUE)
roc9 = roc(test9$Result, test9$Ratio , smooth=TRUE)
g1 <- ggroc(list(roc0=roc0, roc1=roc1, roc2=roc2, roc3=roc3, roc4=roc4, roc5=roc5, roc6=roc6, roc7=roc7, roc8=roc8, roc9=roc9 ))
ggsave(g1, file='roc.test.pdf') 
test_auc_list <- c( auc(roc0), auc(roc1),auc(roc2),auc(roc3),auc(roc4),auc(roc5),auc(roc6),auc(roc7),auc(roc8),auc(roc9))
write.table( test_auc_list, "test.AUC.txt")

#pdf("roc.train.pdf")
roc0 = roc(train0$Result, train0$Ratio ,   auc=TRUE,    grid=TRUE, print.auc=TRUE, show.thres=TRUE, ci=TRUE, boot.n=100, ci.alpha=0.9, stratified=FALSE, smooth=TRUE)
roc1 = roc(train1$Result, train1$Ratio , smooth=TRUE)
roc2 = roc(train2$Result, train2$Ratio , smooth=TRUE)
roc3 = roc(train3$Result, train3$Ratio , smooth=TRUE)
roc4 = roc(train4$Result, train4$Ratio , smooth=TRUE)
roc5 = roc(train5$Result, train5$Ratio , smooth=TRUE)
roc6 = roc(train6$Result, train6$Ratio , smooth=TRUE)
roc7 = roc(train7$Result, train7$Ratio , smooth=TRUE)
roc8 = roc(train8$Result, train8$Ratio , smooth=TRUE)
roc9 = roc(train9$Result, train9$Ratio , smooth=TRUE)
g2 <- ggroc(list(roc0=roc0, roc1=roc1, roc2=roc2, roc3=roc3, roc4=roc4, roc5=roc5, roc6=roc6, roc7=roc7, roc8=roc8, roc9=roc9 ))
ggsave(g2, file='roc.train.pdf')      
train_auc_list <- c( auc(roc0), auc(roc1),auc(roc2),auc(roc3),auc(roc4),auc(roc5),auc(roc6),auc(roc7),auc(roc8),auc(roc9))
write.table(train_auc_list,"train.AUC.txt")

